export const searchStocks = {
	KEYWORD_DATA_FETCHING: "KEYWORD_DATA_FETCHING",
	KEYWORD_DATA_FETCHED: "KEYWORD_DATA_FETCHED",
	KEYWORD_DATA_FETCHING_ERROR: "KEYWORD_DATA_FETCHING_ERROR",
	KEWORD_DATA_RESET: "KEWORD_DATA_RESET"
};

export const stockDetails = {
	STOCK_DATA_FETCHING: "STOCK_DATA_FETCHING",
	STOCK_DATA_FETCHED: "STOCK_DATA_FETCHED",
	STOCK_DATA_FETCHING_ERROR: "STOCK_DATA_FETCHING_ERROR",
	STOCK_DATA_RESET: "STOCK_DATA_RESET",
	STOCK_CHART_FETCHING: "STOCK_DATA_FETCHING",
	STOCK_CHART_FETCHED: "STOCK_CHART_FETCHED"
};
