export const rates = {
	AMOUNT_CHANGED: "amaountChanged",
	CURRENCY_CODE_CHANGED: "currencyCodeChanged",
	RATES_RECEIVED: "ratesReceived"
};

export const searchStocks = {
	KEYWORD_DATA_FETCHING: "KEYWORD_DATA_FETCHING",
	KEYWORD_DATA_FETCHED: "KEYWORD_DATA_FETCHED",
	KEYWORD_DATA_FETCHING_ERROR: "KEYWORD_DATA_FETCHING_ERROR",
	KEWORD_DATA_RESET: "KEWORD_DATA_RESET"
};
